### PR TITLE
Add support for logging the hostname and appname

### PR DESCRIPTION
**Pull request by onno-vos-dev**
Hi there,

To better support logging for servers that have several apps running on them or to allow for a log collector to easily parse the different hostnames that are pushing logs, I've added support for this.

Hostname and appname can be set in the $options array. Default is left to null.

### CODE REVIEW

**Comment by onno-vos-dev** [comment]
Cool @richjenks  Looking forward to your pull request! Any ETA on it? :+1:

**Comment by richjenks** [comment]
I'm aiming for Sunday :)

**Comment by richjenks** [comment]
Can this be closed in light of https://github.com/katzgrau/KLogger/pull/54?

**Comment by onno-vos-dev** [comment]
@katzgrau  Please close in lights of #54

**Comment by katzgrau** [comment]
Good catch

**Pull request closed without merging**
