### PR TITLE
Fix #55: Added ability to register callbacks when logging

### LINKED ISSUE #55: Custom callback
Does anyone think the addition of custom callback feature would be of value? It could be passed the `Logger` object and/or `Logger::lastLine` and would open a lot of possibilities, for example:
- Send an email if the level is `notice` or higher
- Log `emergency` issues to a separate file
- Mirror logs to a database
- Delete/archive log files on a schedule

The developer would have to write the implementations themself (e.g. database connections) but custom callbacks might be a good way to allow advanced logging features without affecting how easy-to-use the basic functions are.

If people think this is of value I'll look into this feature.

### PR DESCRIPTION
**Pull request by richjenks**
Usage all documented in readme

### CODE REVIEW

**Comment by katzgrau** [comment]
I'm kind of mixed on this - I think it could be useful in some cases, but in terms of cleanliness, isn't sub-classing KLogger and overriding the `log` method a better option?

**Comment by richjenks** [comment]
Hi @katzgrau, possibly but my intention was to enable advanced logging features without affecting the ease-of-use of the basic logging function; unless I'm misreading, sub-classing KLogger would require instantiating a different class and while it might be cleaner in some ways it would surely be more confusing to use? Also the `log` method is the latest point at which all the required variables are known so I think it makes sense there.

The primary use-case (which @onno-vos-dev says he uses too) is sending an email notification when a log item is above a certain level which currently requires some sort of wrapper, but if you already have a module for sending email you can hook it directly to KLogger rather than writing a custom wrapper class for each project so I think in that sense it's cleaner.

That said, if you like the idea but not the implementation I'd welcome feedback :)

**Comment by tleb** [comment]
[My bad, posted on the issue, didn't see the issue.](https://github.com/katzgrau/KLogger/issues/55#issuecomment-107148893)

**Comment by richjenks** [comment]
Hi @tleb  not sure if that would be better in this case because it would make KLogger responsive for deciding whether callbacks would run rather than delegating it to the implementation and would require extra code.

My goal was to minimise the impact on KLogger (just a function and an array) and leave the developer to apply conditions to keep it as simple as possible.

@katzgrau do you have an opinion?

**Comment by richjenks** [comment]
Hi @onno-vos-dev, do you have an opinion here? You said in #55 you thought it would be useful so just wanted to see if you still thought so?

**Comment by onno-vos-dev** [comment]
@richjenks I'd say ship it! 

One thing though, wouldn't it be better to have the JSON-logger generate one big JSON-blob instead of each line being JSON-encoded?

It would be harder to implement this but it would make it much easier to make the entire log-file machine readable instead of having to resort to nasty things like json_decode(explode(....).

**Comment by richjenks** [comment]
@onno-vos-dev would do but I don't have write access :)

I like the idea of being able to output one object, but there could be other complications. For one, you wouldn't be logging line-by-line as such and you'd have to do some fancy file-handling to avoid having to read the while file into memory, json decode it, add another item them re-encode and save because of the leading and trailing brackets.

What you could do is add a comma to the end of the format option then do something like `json_decode('['.file_get_contents('log.txt').']')` to read it as one object. Not sure if you'd have to remove the last comma, but it would be cleaner than exploding and decoding in a loop.

Thoughts?

**Comment by onno-vos-dev** [comment]
@richjenks  The more I think about it, the more I agree with you that it would be complicated to implement such a feature. 

One slightly ugly ugly option would be something along the lines of https://github.com/onno-vos-dev/KLogger/commit/9c5a8a00ff74f85af14bd723c4397249bbd5d669

Not the prettiest but it would get the job done and generate a single JSON Blob if this option is set to true in the $options array. 

wdyt?

**Comment by richjenks** [comment]
@onno-vos-dev I think it would be best to have something like that as a separate option as you suggest. We'd have to decide what to do if this option is enabled and there's already a logfile for today. Converting it to a json blob would be a pain but starting a json blob in the middle would be pointless.

Perhaps it should just use a separate file, following the configured filename format plus ".json"?

Either way, it should probably be in another pull request :)

**Comment by onno-vos-dev** [comment]
@richjenks  Agreed with that any of my changes could/should be a separate PR. 

I'd say Ship it! @katzgrau Got time to look it over and merge if you like it? Or do you still have mixed feelings about this?

**Comment by richjenks** [comment]
Hi @katzgrau, what are your current thoughts on this?

**Comment by katzgrau** [comment]
I don't know if I'm being too much of a purist, but subclassing really doesn't seem so complex.

```php
<?php 

use Katzgrau\KLogger\Logger;

class RLogger extends Logger {
    public function log($level, $message, array $context = array())
    {
        // send an email here, if needed
        parent::log($level, $message, $context);
    }
}
```

And in some other file somewhere ...

```php
$logger = new RLogger('./', Psr\Log\LogLevel::DEBUG);
$logger->error('Uh Oh!');
$logger->info('Something Happened Here');
```

I think callbacks can be useful, but in what is probably more of an object-oriented language, it seems a bit unnatural. Counterpoints?

**Comment by richjenks** [comment]
I suppose what we're comparing is the value of a marginally simpler syntax to the weight of extra code. I was going to argue that having easy access to the log data (via https://github.com/richjenks/KLogger/blob/feature/callbacks/src/Logger.php#L222-L232) was an advantage to this feature — while it is a bit nicer to have all that data constructed for you, you could do it all from a subclass and the barrier for entry isn't much higher, plus KLogger wouldn't be doing the extra work every time it logs, whether it's needed or not.

Perhaps then, the solution to the problem of things like email notifications is to change a few things from private to protected (e.g. `$options` and `formatMessage()`) and add some documentation on subclassing use cases rather than this new feature.

What do you think of that as an alternative? I'd be happy to start working on it if you agree.

**Comment by richjenks** [comment]
Hi guys, looks like this dropped of the radar for a while! I had another look and I think I'm leaning towards the extend-with-documentation option so I'm closing this and if you'd like me to augment the docs with a solid example of extending let me know!

**Pull request closed without merging**
