### PR TITLE
Fix cs

### PR DESCRIPTION
**Pull request by Kilte**
Also:
- Added `.gitattributes` to perform LF normalization for text files and exclude tests from arhives.
- Renamed `phpunit.xml` to `phpunit.xml.dist` and added `phpunit.xml` to `.gitignore`

### CODE REVIEW

**Comment by Kilte** [comment]
ping @katzgrau

**Comment by onno-vos-dev** [comment]
@Kilte: The Fact that all of Logger.php is marked as a change doesn't make it easy for Anyone to review this PR. 

Any chance you can fix that?

**Comment by Kilte** [comment]
@onno-vos-dev, I've updated this branch. 
Now you can see changes [here](https://github.com/Kilte/KLogger/commit/04a7edbe4beafcadc21810cf889e4d5f56e8458b).
In [this commit ](https://github.com/Kilte/KLogger/commit/864d760cec18c50d18d50e3a6661713221b54ebc) I've changed line endings, so all of Logger.php is marked as a changed.

Ping @katzgrau  again.

**Comment by katzgrau** [comment]
Thanks for the contrib

**Comment by katzgrau** [comment]
Had to back that out - will update soon

**Pull request merged**
